services:
  postgres:
    image: postgres:15
    container_name: learnapp-postgres
    environment:
      POSTGRES_DB: learnapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - learnapp-pgdata:/var/lib/postgresql/data

volumes:
  learnapp-pgdata:
