ALTER TABLE lectures
    ADD COLUMN IF NOT EXISTS content_status VARCHAR(20) NOT NULL DEFAULT 'NOT_ADDED',
    ADD COLUMN IF NOT EXISTS estimated_minutes INT NOT NULL DEFAULT 60;

ALTER TABLE lectures ADD CONSTRAINT chk_content_status
    CHECK (content_status IN ('NOT_ADDED', 'TRANSCRIPT_ADDED', 'NOTES_GENERATED'));
