ALTER TABLE ai_generations DROP CONSTRAINT IF EXISTS chk_aigen_purpose;
ALTER TABLE ai_generations ADD CONSTRAINT chk_aigen_purpose CHECK (purpose IN (
    'GENERATE_LECTURE_NOTES','EXPLAIN_AGAIN','TUTOR_CHAT',
    'TEACH_BACK_ANALYSIS','SESSION_SUMMARY','TOPIC_NOTE_MERGE',
    'WEAK_AREA_UPDATE','GENERATE_TIMELINE'
));
